name: Deploy Function App Container (Bicep)

on:
  workflow_dispatch:

env:
  DOCKER_IMAGE_NAME: function-app-img

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout repository'
      uses: actions/checkout@v3

    - name: 'Azure login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_RBAC_CREDENTIALS_BICEP }}

    - name: 'Docker login'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER_BICEP }}
        username: ${{ secrets.REGISTRY_USERNAME_BICEP }}
        password: ${{ secrets.REGISTRY_PASSWORD_BICEP }}

    - name: 'Build And Push Docker Image'
      shell: bash
      run: |
        # If your function app project is not located in your repository's root
        # Please change the path to your directory for docker build
        docker build ./src/FunctionAppContainer/FunctionApp -t ${{ secrets.REGISTRY_LOGIN_SERVER_BICEP }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER_BICEP }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}

    - name: 'Deploy Function App Container'
      uses: Azure/functions-container-action@v1
      with:
        app-name: ${{ vars.FUNCTION_APP_NAME_BICEP }}
        image: ${{ secrets.REGISTRY_LOGIN_SERVER_BICEP }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}

    - name: Azure logout
      run: az logout